apiVersion: batch/v1
kind: Job
metadata:
  name: imageinfo-grabber-job
spec:
  template:
    spec:
      containers:
      - name: imageinfo-grabber
        image: mainakmb/imageinfo-grabber:1.0
        env:
        - name: GITHUB_API_TOKEN
          value: "<acccess-key>"
        args: 
        - "https://gist.githubusercontent.com/jmelis/c60e61a893248244dc4fa12b946585c4/raw/25d39f67f2405330a6314cad64fac423a171162c/sources.txt"
      restartPolicy: Never